### ISSUE TITLE
Xray or V2ray?

### ISSUE THREAD

**Issue by ghost** [quintus-lab/NanoPi-R4S-OpenWRT#4]
Hi, I noticed that you no longer have v2ray core here, but Xray core is replaced by it. Is V2ray already in the past? Could you talk about it? The computing power of the rk3399 cpu is not bad, and there is a lot of memory.

**Comment by ghost** [comment]
I try to choose xray ws+TLS, but it does not work. It still can't be used normally 10 minutes after it starts successfully. What am I doing wrong?

**Comment by quintus-lab** [comment]
Maybe need to confirm  VMESS + TLS + WS or VLESS + TLS + WS. 
Xray Core is fully compatible with V2Fly Core.

**Comment by ghost** [comment]
I run successfully with v2rayN on windows10, but it still doesn’t work if I wait for more than 10 minutes on this r4s. May I ask what I did wrong?

**Comment by ghost** [comment]
vless ws TLS with Xray core

**Comment by ghost** [comment]
When I try to start with firmware v1.13, it prompts "Main node: Can't find program, can't start!"

**Comment by quintus-lab** [comment]
Ver1.13 has a mod SSR-plus for test, that is a temporary testing.
It can provided multiple protocols with a xray core,but will causing that you need to  reconfig the server node because the old configuration is no longer compatible.
[V2Ray/XRay: allow protocol selection #316](https://github.com/fw876/helloworld/pull/316)
